def create_categories
  Category.create!(name: 'Chef Special')
  Category.create!(name: 'Beverages')
  Category.create!(name: 'Dessert')
  Category.create!(name: 'Lo Mein and Chow Mein')
  Category.create!(name: 'Vegetables')
  Category.create!(name: 'Seafood')
  Category.create!(name: 'Poultry')
  Category.create!(name: 'Egg Foo Young')
  Category.create!(name: 'Beef')
  Category.create!(name: 'Pork')
  Category.create!(name: 'Fried Rice')
  Category.create!(name: 'Soup')
  Category.create!(name: 'Appetizers')
end